package elasticsearch

type AutoGenerated struct {
	ID                 string `json:"id"`
	RedNumberWeight    string `json:"red_number_weight"`
	AwayLogo1          string `json:"away_logo1"`
	SmallPicURI        string `json:"small_pic_uri"`
	Star               string `json:"star"`
	CreateTime         string `json:"create_time"`
	ExpertsLabel1      string `json:"experts_label1"`
	Rn                 string `json:"rn"`
	LeagueHit          string `json:"league_hit"`
	CloseStatus        string `json:"close_status"`
	ExoertsLabel2      string `json:"exoerts_label2"`
	Trend              string `json:"trend"`
	TotalFans          string `json:"total_fans"`
	Source             string `json:"source"`
	UserNamePc         string `json:"user_name_pc"`
	ExpertsNickName    string `json:"experts_nick_name"`
	ErAgintOrderID     string `json:"er_agint_order_id"`
	TopRedNumWeight    string `json:"top_red_num_weight"`
	ExpertsName        string `json:"experts_name"`
	RecentRecordWeight string `json:"recent_record_weight"`
	LeagueHitWeight    string `json:"league_hit_weight"`
	TotalErCount       string `json:"total_er_count"`
	BiaoStatus         string `json:"biao_status"`
	LeagueName1        string `json:"league_name1"`
	UserIDPc           string `json:"user_id_pc"`
	FiveHitCount       string `json:"five_hit_count"`
	MatchDate1         string `json:"match_date1"`
	HomeName1          string `json:"home_name1"`
	HeadPortrait       string `json:"head_portrait"`
	RecommentComment   string `json:"recomment_comment"`
	ErIssue            string `json:"er_issue"`
	PlayID1            string `json:"play_id1"`
	MatchStatus1       string `json:"match_status1"`
	Prize              string `json:"prize"`
	HitRate            string `json:"hit_rate"`
	FinalWeight        string `json:"final_weight"`
	RecommentExplan    string `json:"recomment_explan"`
	NewStar            string `json:"new_star"`
	MatchDataTime1     string `json:"match_data_time1"`
	SalePrize          string `json:"sale_prize"`
	FiveRecommentCount string `json:"five_recomment_count"`
	IsSale             string `json:"is_sale"`
	Price              string `json:"price"`
	ExpertsClassCode   string `json:"experts_class_code"`
	DateBefore         string `json:"date_before"`
	HomeLogo1          string `json:"home_logo1"`
	AwayName1          string `json:"away_name1"`
	BuyStatus          string `json:"buy_status"`
	RecentRecord       string `json:"recent_record"`
	WeekRate           string `json:"week_rate"`
	RecommentTitle     string `json:"recomment_title"`
	Discount           string `json:"discount"`
	LotteryClassCode   string `json:"lottery_class_code"`
	RedNum             string `json:"red_num"`
	MatchsID1          string `json:"matchs_id1"`
	OverAll            string `json:"over_all"`
	SaleTotalCount     string `json:"sale_total_count"`
	YapanStatus        string `json:"yapan_status"`
	KeepRed            string `json:"keep_red"`
	ExpertDes          string `json:"expert_des"`
	RangStatus         string `json:"rang_status"`
	CloseTime          string `json:"close_time"`
	PlayTypeCode       string `json:"play_type_code"`
	MatchTime1         string `json:"match_time1"`
	TotalSellCount     string `json:"total_sell_count"`
	UserName           string `json:"user_name"`
	SeasonPay          string `json:"season_pay"`
	IsNew              string `json:"is_new"`
	FreeStatus         string `json:"free_status"`
	TopRedNum          string `json:"top_red_num"`
	LevelValue         string `json:"level_value"`
	AddTime            string `json:"add_time"`
	UpdateTime         string `json:"update_time"`
}

type Esconfig struct {
	ES_HOST  string
	ES_PORT  uint32
	ES_INDEX string
	ES_TYPE  string
	ES_SNIFF bool
}
